#!/usr/bin/env python3

import sqlite3
import sys

args = sys.argv

# Connect to the SQLite database (or create it if it doesn't exist)
# path_db = "/Users/jesusbriales/Dropbox/backup/joplin/db_new.sqlite"
path_db = args[1]
conn = sqlite3.connect(path_db)

# Create a cursor object to interact with the database
cursor = conn.cursor()

# Execute a SQL query to read data
cursor.execute("SELECT * FROM notes ORDER BY id ASC")

# Fetch all rows from the executed query
rows = cursor.fetchall()

# Iterate through the rows and print each one
for row in rows:
    id, parent_id, title, body, created_time, updated_time, *_ = row
    # print(id, parent_id, title, body, created_time, updated_time)
    print(id)
    # break

# Close the cursor and connection
cursor.close()
conn.close()

# Compare outputs (find common)
# diff <(/Users/jesusbriales/Code/python/pyjoplin/scripts/read_all db_new.sqlite) <(/Users/jesusbriales/Code/python/pyjoplin/scripts/read_all db_old.sqlite)
# comm -12 <(/Users/jesusbriales/Code/python/pyjoplin/scripts/read_all db_new.sqlite) <(/Users/jesusbriales/Code/python/pyjoplin/scripts/read_all db_old.sqlite)
# 11446 common items
# 11478 in new
# 11488 in old
